spring.application.name=auth-service

server.port= 8082

# spring jdbc properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/ecomexpress_db

# spring data jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.com.ecomexpress.product=DEBUG

# log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# jwt configuration
jwt.secret = myverylongsecretkeythatis256bitforHS256algorithm
